aa: rand-m9-mstd0.5
amp: true
aug_splits: 0
batch_size: 192
bn_eps: null
bn_momentum: null
bn_tf: false
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
data: /home/xihe/datasets/imagenet2012
decay_epochs: 2.4
decay_rate: 0.97
dist_bn: ''
dist_url: tcp://127.0.0.1:8888
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epochs: 450
eval_metric: top1
evalonly: 1
gp: avg
img_size: 224
img_size_teacher: 224
initial_checkpoint: ''
interpolation: ''
jsd: false
kd_ratio: 9.0
knowledge_distill: true
local_rank: 0
log_interval: 100
lr: 0.001
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mask: /home/xihe/xinhe/hyperbox_app/hyperbox_app/distributed/ofa6/train/20221009-193211-ofa/arch.json
mean: null
min_lr: 1.0e-05
mixup: 0.15
mixup_off_epoch: 50
model: ofa
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
momentum: 0.9
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_gpu: 1
ofa_dek: 4,6,7
opt: lookahead_rmsproptf
opt_eps: 0.001
output: ofa6
patience_epochs: 20
pin_mem: false
pretrained: false
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.2
resplit: false
resume: /home/xihe/xinhe/hyperbox_app/hyperbox_app/distributed/ofa6/train/20221009-193211-ofa/model_best.pth.tar
save_images: false
sched: step
seed: 3407
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
teacher_name: D-Net-big224
teacher_off_epoch: 450
train_interpolation: random
tta: 0
use_multi_epochs_loader: false
validation_batch_size_multiplier: 1
warmup_epochs: 3
warmup_lr: 1.0e-06
weight_decay: 1.0e-05
weights: ''
workers: 8
