aa: rand-m9-mstd0.5
amp: true
aug_splits: 0
batch_size: 128
bn_eps: null
bn_momentum: null
bn_tf: false
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
data: /home/xihe/datasets/imagenet2012
decay_epochs: 2.4
decay_rate: 0.97
dist_bn: ''
drop: 0.2
drop_block: null
drop_connect: 0.2
drop_path: null
epochs: 450
eval_metric: top1
finetune: false
gp: avg
img_size: 236
img_size_teacher: 224
initial_checkpoint: ''
interpolation: ''
jsd: false
kd_ratio: 0.0
knowledge_distill: false
local_rank: 0
log_interval: 100
lr: 0.0001
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mask: /home/xihe/xinhe/hyperbox_app/hyperbox_app/distributed/Imagenet_train/scripts/proxylessv1/arch.json
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_off_epoch: 0
model: proxylessnas
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
momentum: 0.9
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_gpu: 1
ofa_dek: 4,6,7
opt: sgd
opt_eps: 1.0e-08
output: ./outputs/proxyless-1.4-v1
patience_epochs: 20
pin_mem: false
pretrained: false
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.2
resplit: false
resume: ''
save_images: false
sched: step
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
teacher_name: ''
teacher_off_epoch: 450
train_interpolation: random
tta: 0
use_multi_epochs_loader: false
validation_batch_size_multiplier: 1
warmup_epochs: 3
warmup_lr: 1.0e-06
weight_decay: 1.0e-05
# weights: /home/comp/18481086/code/hyperbox_app/hyperbox_app/distributed/networks/proxylessnas/hyperbox_proxy_mobile_w1.4.pth
weights: null
workers: 8
