_target_: hyperbox_app.distributed.networks.darts.darts_network.DartsNetwork
in_channels: 3
channels: 16 # 36 for imagenet
n_layers: 8  # 20 for imagenet
stem_multiplier: 3
n_nodes: 4
num_classes: 10
mask: null
# mask: /path/to/hyperbox/hyperbox/networks/darts/darts_mask.json
